StocksApp/ViewModels/Orders.cs
using ServiceContracts.DTOs;

namespace StocksApp.ViewModels
{
    public class Orders
    {
        public List<BuyOrderResponse> BuyOrders { get; set; }
        public List<SellOrderResponse> SellOrders { get; set; }
    }
}

StocksApp/ViewModels/StockTrade.cs
namespace StocksApp.ViewModels
{ 
    public class StockTrade
    {
        public string? StockSymbol { get; set; }
        public string? StockName { get; set; }
        public double Price { get; set; }
        public uint Quantity { get; set; }
    }
}

StocksApp/Components/SelectedStockViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;

namespace StocksApp.Components
{
    public class SelectedStockViewComponent : ViewComponent
    {
        private readonly IFinnhubService _finnhubService;

        public SelectedStockViewComponent(IFinnhubService finnhubService)
        {
            _finnhubService = finnhubService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string stockSymbol)
        {
            var companyProfile = await _finnhubService.GetCompanyProfile(stockSymbol) ?? new();
            var stock = await _finnhubService.GetStockPriceQuote(stockSymbol) ?? new();

            
            if (stock.TryGetValue("c", out var currentPrice))
            {
                companyProfile.Add("price", currentPrice);
            }

            return View(companyProfile);
        }
    }
}

StocksApp/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ServiceContracts;
using StocksApp.Options;
using System.Linq;

namespace StocksApp.Controllers
{
    [Route("[Controller]")]
    public class StocksController : Controller
    {
        private readonly IFinnhubService _finnhubService;
        private readonly IOptions<TradingOptions> _tradingOptions;
        private readonly ILogger<StocksController> _logger;

        public StocksController(IFinnhubService finnhubService, IOptions<TradingOptions> tradingOptions, ILogger<StocksController> logger)
        {
            _finnhubService = finnhubService;
            _tradingOptions = tradingOptions;
            _logger = logger;
        }

        [HttpGet]
        [Route("/")]
        [Route("[Action]")]
        public async Task<IActionResult> Explore(string? stockSymbol, bool showAllStocks = false)
        {
            _logger.LogInformation("Loading Explore Page");
            _logger.LogDebug($"Current Stock Symbol: {stockSymbol}");

            var retrievedStocks = await _finnhubService.GetStocks();
            IEnumerable<Stock> stocks;

            if (!showAllStocks) 
            {
                var stockSymbols = _tradingOptions.Value.Top25PopularStocks?.Split(',') ?? new []{ "MSFT" };

                retrievedStocks = retrievedStocks?.Where(stock => stockSymbols.Contains(stock["symbol"])).ToList() ?? new();

                stocks = retrievedStocks!.Select(retrievedStock => new Stock()
                {
                    StockSymbol = retrievedStock["symbol"],
                    StockName = retrievedStock["description"],
                });
            }
            else
            {
                stocks = retrievedStocks!.Select(retrievedStock => new Stock()
                {
                    StockSymbol = retrievedStock["symbol"],
                    StockName = retrievedStock["description"],
                });
            }

            if (stockSymbol != null)
            {
                ViewData["SelectedStockSymbol"] = stockSymbol;
            }

            return View(stocks);
        }
    }
}

StocksApp/Controllers/TradeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using StocksApp.Options;
using ServiceContracts;
using StocksApp.ViewModels;
using ServiceContracts.DTOs;
using Rotativa.AspNetCore;

namespace StocksApp.Controllers
{
    [Route("[Controller]")]
    public class TradeController : Controller
    {
        private readonly IFinnhubService _finnhubService;
        private readonly IConfiguration _configuration;
        private readonly IStocksService _stocksService;
        private readonly TradingOptions _tradingOptions;
        private readonly ILogger<TradeController> _logger;

        public TradeController(IFinnhubService myService, IConfiguration configuration, IStocksService stocksService, IOptions<TradingOptions> tradingOptions, ILogger<TradeController> logger)
        {
            _finnhubService = myService;
            _configuration = configuration;
            _stocksService = stocksService;
            _tradingOptions = tradingOptions.Value;
            _logger = logger;
        }

        [HttpGet]
        [Route("[Action]/{stockSymbol}")]
        [Route("~/[controller]/{stockSymbol}")]
        public async Task<IActionResult> Index(string stockSymbol)
        {
            _logger.LogInformation($"Loading Trade/Index with stock symbol: {stockSymbol}");

            if (string.IsNullOrEmpty(stockSymbol))
            {
                stockSymbol = "MSFT";
            }

            var company = await _finnhubService.GetCompanyProfile(stockSymbol);
            var stock = await _finnhubService.GetStockPriceQuote(stockSymbol);

            var stockTrade = new StockTrade() { StockSymbol = stockSymbol };
            
            if (stock != null && company != null)
            {
                stockTrade = new StockTrade() 
                { 
                    StockSymbol = company["ticker"].ToString(), 
                    StockName = company["name"].ToString(), 
                    Quantity = Convert.ToUInt32(_tradingOptions.DefaultOrderQuantity), 
                    Price = Convert.ToDouble(stock["c"].ToString()) 
                };
            }

            ViewData["ApiKey"] = _configuration["FinnhubToken"];
            return View(stockTrade);
        }

        [HttpGet]
        [Route("[Action]")]
        public async Task<IActionResult> Orders()
        {
            var buyOrders = await _stocksService.GetAllBuyOrders();
            var sellOrders = await _stocksService.GetAllSellOrders();

            var orders = new Orders()
            {
                BuyOrders = buyOrders,
                SellOrders = sellOrders,
            };

            return View(orders);
        }

        [HttpGet]
        [Route("[Action]")]
        public async Task<IActionResult> OrdersPDF()
        {
            var buyOrders = await _stocksService.GetAllBuyOrders();
            var sellOrders = await _stocksService.GetAllSellOrders();

            var orders = ((IEnumerable<IOrderResponse>)buyOrders).Concat(sellOrders).OrderByDescending(order => order.DateAndTimeOfOrder).ToList();

            return new ViewAsPdf("OrdersPDF", orders)
            {
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Bottom = 20, Left = 20, Right = 20 },
            };
        }

        [HttpPost]
        [Route("[Action]")]
        public async Task<IActionResult> BuyOrder(BuyOrderRequest buyOrderRequest)
        {
            ModelState.Remove("DateAndTimeOfOrder");
            if (ModelState.IsValid)
            {
                buyOrderRequest.DateAndTimeOfOrder = DateTime.Now;

                await _stocksService.CreateBuyOrder(buyOrderRequest);

                return RedirectToAction("Orders", "Trade");
            }

            return RedirectToAction("Index", "Trade");
        }


        [HttpPost]
        [Route("[Action]")]
        public async Task<IActionResult> SellOrder(SellOrderRequest sellOrderRequest)
        {
            ModelState.Remove("DateAndTimeOfOrder");
            if (ModelState.IsValid)
            {
                sellOrderRequest.DateAndTimeOfOrder = DateTime.Now;

                await _stocksService.CreateSellOrder(sellOrderRequest);

                return RedirectToAction("Orders", "Trade"); 
            }

            return RedirectToAction("Index", "Trade");
        }
    }
}

StocksApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" charset="utf-8" />
    <title>@ViewBag.Title</title>
    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>
<body>
    <div class="container">
        <div class="flex mt mb">
            <div class="flex-1" id="app-title-div">
                <h1 class="app-title">
                    <i class="fa-solid fa-money-bill-trend-up"></i>
                    Stocks
                </h1>
            </div>
            <div class="flex text-right" style="align-items: center;">
                <input type="search" class="search-text" placeholder="Search Stocks"/>
                <a href="#" style="margin-left: 5px; margin-right: 25px;">
                    <i class="fa-solid fa-gear" style="color: black;"></i>
                </a>
                <button class="button login-button button-blue-back">Login</button>
            </div>
        </div>
        <div class="navbar flex">
            <div class="flex">
                <a asp-action="Explore" asp-controller="Stocks" class="link-hover @(ViewBag.ActivePage != null && ViewBag.ActivePage == "Trade/Explore" ? "nav-active" : "")" style="text-decoration: none; color: #0349A3;">Explore</a>
                <div style="margin: 0 5px;"></div>
                <a asp-action="Index" asp-controller="Trade" class="link-hover @(ViewBag.ActivePage != null && ViewBag.ActivePage == "Trade/Index" ? "nav-active" : "")" style="text-decoration: none; color: #0349A3;">Trade</a>
                <div style="margin: 0 5px;"></div>
                <a asp-action="Orders" asp-controller="Trade" class="link-hover @(ViewBag.ActivePage != null && ViewBag.ActivePage == "Trade/Orders" ? "nav-active" : "")" style="text-decoration: none; color: #0349A3;">Orders</a>
            </div>
        </div>

        @RenderBody()

        @RenderSection("Scripts", false);
    </div>
</body>
</html>

StocksApp/Views/Stocks/Components/SelectedStock/Default.cshtml
@model Dictionary<string, object>?

<img src="@Model["logo"]" style="width: 200px" alt="company-logo" />
<h2>@($"{Model["name"]} ({Model["ticker"]})")</h2>
<span class="pill">@Model["finnhubIndustry"]</span>

<h3>Exchange: <span class="pill" style="font-size: 24px;">@Model["exchange"]</span></h3>

<h1 class="stock-price mb"><span class="text-grey">$</span> @Model["price"]</h1>

<a asp-action="Index" asp-controller="Trade" asp-route-stockSymbol="@Model["ticker"]" class="button button-blue-back mt" style="text-decoration: none; color: white;">Trade Now</a>

StocksApp/Views/Stocks/Explore.cshtml
@model IEnumerable<Stock>

@{
    ViewData["Title"] = "Explore";
    ViewData["ActivePage"] = "Stocks/Explore";
}

<div class="flex ml mt">
    <div class="flex-1">
        <p class="text-grey">Stocks <i class="fa-solid fa-caret-right"></i> @ViewBag.Title</p>
    </div>
</div>
<div class="flex">
    <div class="flex-1 flex-direction-vertical box" style="padding: 20px;">
        <div class="flex" style="justify-content: space-between; align-items: center;">
            <h3 class="text-grey">Stocks</h3>
            <a asp-action="Explore" asp-controller="Stocks" asp-route-showAllStocks="true">Show all stocks</a>
        </div>

        <div class="flex-1 mt mb">
            @foreach (var stock in Model)
            {
                <a asp-action="Explore" asp-controller="Stocks" asp-route-stockSymbol="@stock.StockSymbol" style="text-decoration: none; color: black;">
                    <div class="box">
                        <h1>@stock.StockName</h1>
                        <h5 class="text-grey">@($"({@stock.StockSymbol})")</h5>
                    </div>
                </a>
            }
        </div>
    </div>
    <div class="flex-1 flex-direction-vertical">
        @if (ViewBag.SelectedStockSymbol != null)
        {
            @(await Component.InvokeAsync("SelectedStock", new { stockSymbol = ViewBag.SelectedStockSymbol }))
        }
    </div>
</div>

StocksApp/Views/Trade/Index.cshtml
@model StockTrade

@{
    ViewData["Title"] = "Microsoft Corp";
    ViewData["ActivePage"] = "Trade/Index";
}

<input type="hidden" id="apiKey" value="@ViewBag.ApiKey" />

<div class="flex ml mt">
    <p class="text-grey">Stocks <i class="fa-solid fa-caret-right"></i> @ViewBag.Title</p>
</div>
<div class="box trading-panel">
    <div class="flex trading-panel-flex">
        <div id="stock-price-panel" style="display: flex; align-items: center;">
            <div class="flex flex-direction-vertical">
                <h3 class="text-blue">@Model.StockName (@Model.StockSymbol)</h3>
                <h1><small class="text-grey">$</small> <span class="price">@Model.Price.ToString("N")</span></h1>
            </div>
        </div>
        <div class="flex border-left"></div>
        <div class="flex flex-direction-vertical margin-auto" style="align-items: center; justify-content: center; padding: 25px 0">
            <div class="flex-1">
                <h3 class="text-grey">New Order</h3>
            </div>
            <form id="orderForm" method="post">
                <div class="flex-1 mt mb">
                    <div>
                        <label asp-for="Quantity">Quantity:</label>
                    </div>
                    <input type="number" asp-for="Quantity" class="form-input" style="width: 100px"/>
                    <span asp-validation-for="Quantity"></span>
                </div>
                <div class="flex-1 mt" style="margin-top: 15px">
                    <input type="hidden" id="stockSymbol" asp-for="StockSymbol" />
                    <input type="hidden" asp-for="StockName" />
                    <input type="hidden" asp-for="Price" />
                    <button type="submit" class="button button-red-back" asp-action="SellOrder" asp-controller="Trade" style="margin-right: 8px;"><i class="fa-solid fa-arrow-down"></i> Sell</button>
                    <button type="submit" class="button button-green-back" asp-action="BuyOrder" asp-controller="Trade"><i class="fa-solid fa-arrow-up"></i> Buy</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/StocksApp.js"></script>
}

StocksApp/Views/Trade/Orders.cshtml
@model Orders

@{
    ViewData["Title"] = "Orders";
    ViewData["ActivePage"] = "Trade/Orders";
}

<div class="flex ml mt">
    <div class="flex-1">
        <p class="text-grey">Stocks <i class="fa-solid fa-caret-right"></i> @ViewBag.Title</p>
    </div>
    <div class="flex-1 text-right mr">
        <a asp-action="OrdersPDF" asp-controller="Trade">Download as PDF</a>
    </div>
</div>
<div class="flex">
    <div class="flex-1 flex-direction-vertical box" style="padding: 20px;">
        <div class="flex">
            <h3 class="text-grey">Buy Orders</h3>
        </div>

        <div class="flex-1 mt mb">
            @foreach (var buyOrder in Model.BuyOrders)
            {
                <div class="flex flex-direction-vertical mt" style="padding: 0 5px;">
                    <h2 class="mt">@buyOrder.StockName (@buyOrder.StockSymbol)</h2>
                    <h4 class="mb">@buyOrder.Quantity <span class="text-grey">shares at</span> $@buyOrder.Price.ToString("N")</h4>
                    <h4 class="mb"><span class="text-grey">Trade Amount: </span>$@((buyOrder.Price * buyOrder.Quantity).ToString("N"))</h4>
                    <p class="text-grey mb" style="font-size: 24px">@buyOrder.DateAndTimeOfOrder.ToString("dd MMMM yyyy hh:mm:ss tt").Replace("am", "AM").Replace("pm", "PM")</p>
                </div>
                <div class="border-bottom">
                </div>
            }
        </div>
    </div>
    <div class="flex-1 flex-direction-vertical box" style="padding: 20px;">
        <div class="flex">
            <h3 class="text-grey">Sell Orders</h3>
        </div>

        <div class="flex-1 mt mb">
            @foreach (var sellOrder in Model.SellOrders)
            {
                <div class="flex flex-direction-vertical mt" style="padding: 0 5px;">
                    <h2 class="mt">@sellOrder.StockName (@sellOrder.StockSymbol)</h2>
                    <h4>@sellOrder.Quantity <span class="text-grey">shares at</span> $@sellOrder.Price.ToString("N")</h4>
                    <h4 class="mb"><span class="text-grey">Trade Amount: </span>$@((sellOrder.Price * sellOrder.Quantity).ToString("N"))</h4>
                    <p class="text-grey mb" style="font-size: 24px">@sellOrder.DateAndTimeOfOrder.ToString("dd MMMM yyyy hh:mm:ss tt").Replace("am", "AM").Replace("pm", "PM")</p>
                </div>
                <div class="border-bottom">
                </div>
            }
        </div>
    </div>
</div>

StocksApp/Views/Trade/OrdersPDF.cshtml
@model IEnumerable<IOrderResponse>

@{
    Layout = null;
}

<link rel="stylesheet" href="@($"http://{Context.Request.Host.ToString()}/css/Stylesheet.css")" />
<h1 class="mb">Orders</h1>
<table class="table w-100" style="margin: 0; padding: 0;">
    <thead>
        <tr>
            <th>Date and Time</th>
            <th>Stock</th>
            <th>Order Type</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Trade Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.DateAndTimeOfOrder.ToString("dd MMMM yyyy hh:mm:ss tt").Replace("am", "AM").Replace("pm", "PM")</td>
                <td>@($"{order.StockName} ({order.StockSymbol})")</td>
                <td>@(order is BuyOrderResponse ? "BuyOrder" : "SellOrder")</td>
                <td>@order.Quantity</td>
                <td>@($"$ {order.Price}")</td>
                <td>@((order.Price * order.Quantity).ToString("N"))</td>
            </tr>
        }
    </tbody>
</table>